### ISSUE TITLE
gmock not found

### ISSUE THREAD

**Issue by kolsha** [MarkusJx/googletest-installer#2]
Hi!
You also need to copy gmock headers:
```shell
sudo cp -R googletest/googlemock/include/gmock /usr/include
```

**Comment by kolsha** [comment]
@MarkusJx MarkusJx will you create a new release?

**Comment by MarkusJx** [comment]
Yeah, right, forgot about that. I'll create one soon

**Comment by MarkusJx** [comment]
Done: https://github.com/MarkusJx/googletest-installer/releases/tag/v1.1.1
